name: Jekyll Build and Deploy

on:
  [workflow_dispatch, push]

jobs:
  convert_to_pdf:
    runs-on: ubuntu-latest
    container:
      image: docker://pandoc/latex:2.9
      options: --entrypoint=sh
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: create file list
      id: files_list
      run: |
        mkdir output  # create output dir
        for i in *.md; do pandoc  -f markdown -t pdf --file-scope -o output/$i.pdf $i; done
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y_%m_%d')" >> "$GITHUB_OUTPUT"

    - name: Create tag
      uses: actions/github-script@v5
      with:
        script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{steps.date.outputs.date}}',
              sha: context.sha
            })
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{steps.date.outputs.date}}
        files: |
          output/*
    
    

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0

    - name: install
      working-directory: docs/jekyll
      run: |
        gem install bundler jekyll 
        bundle install
    - name: Build 
      working-directory: docs/jekyll
      run: |
        mkdir ../build
        JEKYLL_ENV=production bundle exec jekyll build --trace --source ${{github.workspace}}/docs/jekyll --destination ${{github.workspace}}/docs/build
        touch ${{github.workspace}}/docs/build/.nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ${{github.workspace}}/docs/build
        publish_branch: gh-pages
