name: Jekyll Build and Deploy

on:
  [workflow_dispatch, push]

jobs:
  convert_to_pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - uses: docker://pandoc/core:2.9
      with:
        args: "*.md -f markdown -t pdf --file-scope -o output.pdf" 

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: converted-pdf
        path: pdf/output.pdf

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0

    - name: install
      working-directory: docs/jekyll
      run: |
        gem install bundler jekyll 
        bundle install
    - name: Build 
      working-directory: docs/jekyll
      run: |
        JEKYLL_ENV=production bundle exec jekyll build --trace --source ${{github.workspace}}/docs/jekyll --destination ${{github.workspace}}/docs
        touch ${{github.workspace}}/docs/.nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ${{github.workspace}}/docs/
        publish_branch: gh-pages
